### PR TITLE
[FIX] #83 added support for RemoteFile files

### LINKED ISSUE #83: Unable to log remote files
https://github.com/wakatime/atom-wakatime/blob/master/lib/wakatime.coffee#L451

when working with remote files, the `file` object is of type `RemoteFile`, which doesn't have a `path` property; it has a `getPath` method instead.

This causes any work on remote files to not be logged:
```
[WakaTime] [DEBUG] [wakatime.coffee:452] Skipping file because path does not exist: undefined
```

### PR DESCRIPTION
**Pull request by bradzacher**
Fixes #83

### CODE REVIEW

**Comment by alanhamlett** [comment]
Cool! Does this log coding against that file to your dashboard? Asking because another piece in the puzzle is https://github.com/wakatime/wakatime/issues/72 because the core Python component only supports reading local files.

What's the file path prefix for your remote file?

**Comment by bradzacher** [comment]
looking at my .wakatime.log file... it complains about the file not existing 😅
I didn't check there because I didn't realise that the cli did that - I only confirmed that the plugin code passed it to the cli fine!

I'm using nuclide, so my remote files all follow the format `nucilde://<server>/<path>`

**Comment by alanhamlett** [comment]
According to [Nuclide Remote Development doc](https://nuclide.io/docs/features/remote/) it's using SSH to connect to to the remote server hosting your remote files. Once SSH support is implemented with https://github.com/wakatime/wakatime/issues/72 then it will work.

**Comment by alanhamlett** [comment]
Just curious, with Nuclide what do you get with `file.getLocalPath()` instead of `file.getPath()`?

**Comment by alanhamlett** [comment]
Then tracking remote files will only work after SSH support is added to [wakatime](https://github.com/wakatime/wakatime).

**Pull request merged**
